name: deploy-toy-website-environments
concurrency: toy-company

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Lint the Bicep file
  lint:
    uses: fwestling-lor/toy-website-environments/.github/workflows/lint.yml@main

  deploy-test:
    uses: fwestling-lor/toy-website-environments/.github/workflows/deploy.yml@main
    needs: lint
    with:
      environmentType: Test
      resourceGroupName: ToyWebsiteTest
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_TEST }}

  deploy-production:
    uses: fwestling-lor/toy-website-environments/.github/workflows/deploy.yml@main
    needs: deploy-test
    with:
      environmentType: Production
      resourceGroupName: ToyWebsiteProduction
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_PRODUCTION }}
